Traceback (most recent call last):
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')

import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from orodja import plot_mode_shape
from ipywidgets import interact

import lvm_read
import pyidi
import pyEMA
from sdypy import FRF as  pyFRF
------------------

----- stderr -----
C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\site-packages\napari\layers\utils\layer_utils.py:10: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
----- stderr -----
C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\copy.py:151: DeprecationWarning: Pickle, copy, and deepcopy support will be removed from itertools in Python 3.14.
  rv = reductor(4)
C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\copy.py:261: DeprecationWarning: Pickle, copy, and deepcopy support will be removed from itertools in Python 3.14.
  y.__setstate__(state)
----- stderr -----
C:\Users\Domen\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyEMA\__init__.py:12: UserWarning: This is the last version of pyEMA and will not longer be maintained since it is moving to the SDyPy package. To use the latest code from SDyPy: `pip install sdypy` and `from sdypy import EMA`.
  warnings.warn('This is the last version of pyEMA and will not longer be maintained since it is moving to the SDyPy package. To use the latest code from SDyPy: `pip install sdypy` and `from sdypy import EMA`.')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[1], line 15[0m
[0;32m     13[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyidi[39;00m
[0;32m     14[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyEMA[39;00m
[1;32m---> 15[0m [38;5;28;01mfrom[39;00m [38;5;21;01msdypy[39;00m [38;5;28;01mimport[39;00m FRF [38;5;28;01mas[39;00m  pyFRF

[1;31mImportError[0m: cannot import name 'FRF' from 'sdypy' (unknown location)

