Traceback (most recent call last):
  File "d:\pedago≈°ko\_Procesiranje signalov\_VAJE\ps_lv\venv\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "d:\pedago≈°ko\_Procesiranje signalov\_VAJE\ps_lv\venv\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "d:\pedago≈°ko\_Procesiranje signalov\_VAJE\ps_lv\venv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "d:\pedago≈°ko\_Procesiranje signalov\_VAJE\ps_lv\venv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Domen\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "d:\pedago≈°ko\_Procesiranje signalov\_VAJE\ps_lv\venv\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "d:\pedago≈°ko\_Procesiranje signalov\_VAJE\ps_lv\venv\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "d:\pedago≈°ko\_Procesiranje signalov\_VAJE\ps_lv\venv\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
V `Case` stavku se, na podlagi izbranega pogoja, odloƒçimo, kateri 
------------------

[1;36m  Input [1;32mIn [1][1;36m[0m
[1;33m    V `Case` stavku se, na podlagi izbranega pogoja, odloƒçimo, kateri[0m
[1;37m      ^[0m
[1;31mSyntaxError[0m[1;31m:[0m invalid syntax

SyntaxError: invalid syntax (2471063176.py, line 1)

